{{- if .Values.persistentVolume.enabled }}
{{- if not .Values.persistentVolume.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-pvc
  labels:
{{ include "labels.standard" . | indent 4 }}
  annotations:
  {{- if .Values.persistentVolume.annotations }}
{{ toYaml .Values.persistentVolume.annotations | indent 4 }}
  {{- end }}
spec:
  accessModes:
{{ toYaml .Values.persistentVolume.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size | quote }}
{{- end }}
{{- end }}
