dependencies:
- name: redis
  version: 0.9.0
  repository: http://liaoj-helm-repository.e2equota.haproxy-139-219-56-162-alaudaorg.myalauda.cn/
- name: postgresql
  version: 0.8.1
  repository: http://liaoj-helm-repository.e2equota.haproxy-139-219-56-162-alaudaorg.myalauda.cn/
